# Generated by Django 4.2.1 on 2023-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
            ],
        ),
    ]
