# Generated by Django 4.2.1 on 2023-06-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_table',
            old_name='day',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='age_table',
            old_name='month',
            new_name='birth_month',
        ),
        migrations.RenameField(
            model_name='age_table',
            old_name='year',
            new_name='birth_year',
        ),
    ]
